Input definition being nullable if default value is provided
fsprojects/FSharp.Data.GraphQL pull request #168
Opened 2018-07-02 22:33 UTC by ivelten

This PR is a fix proposal for the issue reported [here](https://github.com/fsprojects/FSharp.Data.GraphQL/issues/167).

It makes a input field definition automatically as a nullable value, when a default value is provided.

2018-07-03 04:50 UTC, Horusiath requested changes

2018-07-03 04:50 UTC, Horusiath commented on src/FSharp.Data.GraphQL.Server/Schema.fs
> +              DefaultValue = Some defaultValue |> Option.map string }
Use `Some (string defaultValue)` - Option.map can potentially create another option, while there's no need for that.

2018-07-03 04:50 UTC, Horusiath commented on src/FSharp.Data.GraphQL.Server/Schema.fs
> +              Type = introspectTypeRef true namedTypes inputDef.TypeDef
This can actually be written as `(Option.isSome inputDef.DefaultValue)` - in that case you won't need pattern match at all.

2018-07-03 04:54 UTC, Horusiath commented
2 more issues:

1. You're committing 10 000 LOC for the sake of having paket lock file - this seems unjustified (especially since the change itself is 1 line of code).
2. There are not tests to actually verify that this change solved an issue.

2018-07-05 21:16 UTC, ivelten commented on src/FSharp.Data.GraphQL.Server/Execution.fs
> -let private optionCast (value: obj) =
I took out those functions and put them on the Shared library, because I wanted to use them on another piece of code for this issue.

2018-08-13 18:16 UTC, ivelten commented
@Horusiath could you give another look into this PR? I have made all the changes you asked for.

2018-09-01 10:54 UTC, Horusiath approved these changes

2018-09-01 21:16 UTC, merged