Fix introspection for Servers expecting Post
fsprojects/FSharp.Data.GraphQL pull request #273
Opened 2020-03-28 13:21 UTC by Birnsen

It is possible that a Get Request is successful
but does not contain a proper schema.

With this commit if a Get Requests succeds it
will be checked if a schema can be deserialized.
If not a Post request is taking place and also
checked for a proper schema.

2022-12-05 22:35 UTC, xperiandri requested changes

2022-12-05 22:35 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Client/GraphQLClient.fs
>          let sendGet() = async { return! getAsync connection.Client serverUrl }
Why do we need to wrap that?
```suggestion
        let sendGetAsync() = getAsync connection.Client serverUrl
```

2022-12-07 20:16 UTC, xperiandri approved these changes

2022-12-07 20:19 UTC, xperiandri commented
Could you rebase and solve conflicts, please?

2022-12-07 21:02 UTC, Birnsen commented
I currently have no access to a Dev-Environmnt and the PR is rather old, so I do not know if the Rebase worked correctly.

2024-09-01 15:15 UTC, closed without merging

2024-09-01 15:15 UTC, xperiandri commented
This is handled in the latest versions