Support recursive field definition
fsprojects/FSharp.Data.GraphQL pull request #349
Opened 2021-09-21 06:39 UTC by vanhoeij

Using recursive definition of fields in the `InputObject` resulted in a null reference exception. The exception was triggered because the `ExecuteInput` on a field definition was not initialized. It was caused by not caching the field definitions correctly, resulting in uninitialized field definitions to be used.

In this PR, the function that is used to retrieve the definitions is wrapped inside a lazy, which makes sure that always the same field definitions are returned.

ps. it was required to update the dependencies because `MSBuild.StructuredLogger` was causing an issue when restoring the client project.

2022-03-03 06:10 UTC, jberzy requested changes
Very Nice. Can we just remove that build.fsx.lock changes and I think this is good to go.

2022-05-19 18:22 UTC, xperiandri commented
@mickhansen, @nikhedonia any comments about this one?

2022-09-10 22:00 UTC, xperiandri requested changes
@vanhoeij will you rebase this on top of the latest changes?

2022-09-10 22:00 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Shared/TypeSystem.fs
> +      FieldsFn : Lazy<InputFieldDef[]> }
```suggestion
      Fields : Lazy<InputFieldDef[]> }
```
As we release v2 I think we can rename it

2022-10-07 22:18 UTC, xperiandri commented
@vanhoeij

2022-10-07 22:18 UTC, xperiandri commented
@vanhoeij

2022-10-07 22:18 UTC, xperiandri commented
@njlr what do you think?

2022-10-08 15:02 UTC, njlr commented
> @njlr what do you think?

This change makes sense to me. 

Good to fix the typos also :+1:

2022-11-27 01:30 UTC, xperiandri commented
@vanhoeij will you rebase?
Or give me access to your repo

2022-12-05 22:26 UTC, xperiandri approved these changes

2022-12-05 22:27 UTC, xperiandri commented
@vanhoeij thank you very much for your contribution!

2022-12-05 22:36 UTC, xperiandri commented
@vanhoeij 
```
Error Message:
   expected { fieldWithNestedInputObject: "{"na":{"a":null,"b":null,"c":"c","d":null},"nb":"b"}" }
but got { fieldWithNestedInputObject: "{"na":{"a":null,"b":null,"c":"c","d":null,"e":null},"nb":"b"}" }
```

2022-12-05 22:39 UTC, xperiandri commented
Is the fix is as simple as adding `,"e":null`?

2022-12-06 12:11 UTC, xperiandri approved these changes

2022-12-06 12:44 UTC, merged