support using DUs as Enum variables
fsprojects/FSharp.Data.GraphQL pull request #357
Opened 2022-02-23 09:11 UTC by mickhansen

2022-02-24 11:54 UTC, sgryt commented
@mickhansen Looks good to me.

2022-03-11 03:17 UTC, jberzy requested changes

2022-03-11 03:17 UTC, jberzy commented on tests/FSharp.Data.GraphQL.Tests/VariablesTests.fs
> +    let expected = NameValueLookup.ofList [ "fieldWithNullableEnumInput", upcast "{\"case\":\"Bar\"}" ]
Since DUs are represented differently than Enums, and that only DUs that don't contain parameters are valid in this case, maybe we should add a JsonSerializer that overrides the default Json.NET encoding and strips the outer "case" portion i.e. the "Tag" becomes the json string result making the output identical to the Enum handler.

2022-03-11 03:17 UTC, jberzy commented on build.fsx
> +            { options with MSBuildParams = { options.MSBuildParams with DisableInternalBinLog = true } }
Does that solve a build issue?

2022-03-11 03:19 UTC, mickhansen commented on build.fsx
> +            { options with MSBuildParams = { options.MSBuildParams with DisableInternalBinLog = true } }
@jberzy Yes it solved the OS X build issue we've been having on GitHub (and also solves a local build issue of mine)

2022-03-11 03:21 UTC, mickhansen commented on tests/FSharp.Data.GraphQL.Tests/VariablesTests.fs
> +    let expected = NameValueLookup.ofList [ "fieldWithNullableEnumInput", upcast "{\"case\":\"Bar\"}" ]
@jberzy We could but I don't think it has any meaningful implications for production code. The resolver for this test simply stringifies whatever it's given and that's why we end up with `case:`, I don't think people would write resolvers like that in real code, and if they did they can control how it's stringified.

2022-03-11 03:22 UTC, mickhansen commented on tests/FSharp.Data.GraphQL.Tests/VariablesTests.fs
> +    let expected = NameValueLookup.ofList [ "fieldWithNullableEnumInput", upcast "{\"case\":\"Bar\"}" ]
What I mean is that this output is the direct result of using `stringifyInput` further up in the test code, it's not being produced by the library itself.

2022-03-15 07:08 UTC, jberzy commented on tests/FSharp.Data.GraphQL.Tests/VariablesTests.fs
> +    let expected = NameValueLookup.ofList [ "fieldWithNullableEnumInput", upcast "{\"case\":\"Bar\"}" ]
Ok, that's fine. We can have a separate PR address adding custom Json Converters. Maybe after we merge the support for System.Text.Json.

2022-03-15 07:09 UTC, jberzy commented
LGTM. Thanks!

2022-03-15 07:09 UTC, merged