Added NuGet dependencies between packages
fsprojects/FSharp.Data.GraphQL pull request #413
Opened 2022-12-13 12:32 UTC by Juriyx

2022-12-13 13:35 UTC, xperiandri requested changes

2022-12-13 13:35 UTC, xperiandri commented on Directory.Build.targets
> +    <Version>1.0.0</Version>
А чего ты на 1 поменял? У нас будет вторая версия

2022-12-13 13:35 UTC, xperiandri commented on .github/workflows/publish_release.yml
> +        dotnet test --configuration Release --no-restore --no-build
Не, так не проканает. В это м проекте или папке тестов нет

2022-12-13 13:35 UTC, xperiandri commented on .github/workflows/publish_release.yml
>          dotnet pack --nologo --configuration Release /p:IsNuget=true -o ../../nuget
Чтобы прогнать тесты тебе нужно построить решение, а потом прогнать тесты с флагом `--no-build` и только потом уже паковать с флагом `--no-build`

2022-12-13 13:35 UTC, xperiandri commented on .github/workflows/publish_ci.yml
> +        dotnet test --configuration Release --no-restore --no-build
Точно так же и здесь

2022-12-13 15:03 UTC, Juriyx commented on Directory.Build.targets
> +    <Version>1.0.0</Version>
Для теста нужно было. Забыл вернуть назад

2022-12-14 22:42 UTC, xperiandri requested changes

2022-12-14 22:42 UTC, xperiandri commented on .github/workflows/publish_ci.yml
> +        dotnet nuget push ../../nuget/*Shared*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}}
What was the reason to split that into 2 steps?

2022-12-14 22:42 UTC, xperiandri commented on .github/workflows/publish_ci.yml
> +        dotnet nuget push ../../nuget/*Shared*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}}
What was the reason to split that into 2 steps?

2022-12-17 18:03 UTC, xperiandri approved these changes

2022-12-17 18:04 UTC, merged

2022-12-17 18:36 UTC, xperiandri commented
@njlr packages are in the GitHub feed