bugfix/issue-414-enum-unpacking
fsprojects/FSharp.Data.GraphQL pull request #415
Opened 2022-12-14 19:05 UTC by njlr

Fix for https://github.com/fsprojects/FSharp.Data.GraphQL/issues/414

2022-12-14 22:37 UTC, xperiandri requested changes
Could you highlight (comment) a piece of code that does a fix.
I cannot figure it out because of formatting

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +                    raise (GraphQLException (errMsg + notAssignableMsg innerdef coerced))
```suggestion
                    raise <| GraphQLException (errMsg + notAssignableMsg innerdef coerced)
```

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +                )
```suggestion
                else raise <| GraphQLException ($"%s{errMsg}value of type %O{coerced.GetType()} is not assignable from %O")
```

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +            )
``` suggestion
        | null -> raise <| GraphQLException ($"%s{errMsg}expected value of type %s{vardef.TypeDef.ToString()}, but no value was found.")
```

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +            )
``` suggestion
        | other -> raise <| GraphQLException ($"{errMsg}Cannot coerce value of type '%O{other.GetType()}' to list.")
```

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +            )
```suggestion
        | null -> raise <| GraphQLException ($"%s{errMsg}Expected Enum '%s{enumdef.Name}', but no value was found.")

```

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +            )
``` suggestion
         | _ -> raise <| GraphQLException ($"%s{errMsg}Cannot coerce value of type '%O{input.GetType()}' to type Enum '%s{enumdef.Name}'")

```

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +        )
```suggestion
    | _ -> raise <| GraphQLException ($"%s{errMsg}Only Scalars, Nullables, Lists, and InputObjects are valid type definitions.")
```

2022-12-14 22:37 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +            | _ -> raise (GraphQLException (sprintf "Variable '$%s' of required type %s has no value provided." vname (vardef.TypeDef.ToString ())))
```suggestion
            | _ -> raise <| GraphQLException ($"Variable '$%s{vname}' of required type '%s{vardef.TypeDef.ToString ()}' has no value provided.")
```

2022-12-14 23:46 UTC, njlr commented
> Could you highlight (comment) a piece of code that does a fix? I cannot figure it out because of formatting

Sorry, I ran Fantomas since I thought that was the policy going forward. 

You can see the logic changes in the first commit: https://github.com/fsprojects/FSharp.Data.GraphQL/pull/415/commits/e4b6e90e6e5183ac22cc838a0368b6ab4b09fee3

2022-12-15 00:01 UTC, xperiandri commented
Thanks. Looks good. Let's reformat exceptions raising and we a good to merge

2022-12-15 10:00 UTC, njlr commented
> Thanks. Looks good. Let's reformat exceptions raising and we a good to merge

Addressed. Please squash this on merging - GitHub's "commit suggestion" feature is not ideal

BTW, is there a plan for when the next release of this library will land?

2022-12-15 17:27 UTC, xperiandri requested changes
A few more strings

2022-12-15 17:27 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +                   + (sprintf "expected value of type %s but got None" scalardef.Name)
```suggestion
                <| $"%s{errMsg}expected value of type %s{scalardef.Name} but got None")
```

2022-12-15 17:27 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +                   + (sprintf "Cannot coerce value of type '%O' to type Enum '%s'" (input.GetType ()) enumdef.Name)
```suggestion
                <| $"%s{errMsg}Cannot coerce value of type '%O{input.GetType ()}' to type Enum '%s{enumdef.Name}'")
```

2022-12-15 17:28 UTC, xperiandri commented
@njlr yes I'll squash
@Juriyx almost finished a pipeline. So you will be able to consume this fixes at least fro GitHub feed the next week.
Release of 2.0 I suppose till the end of the year or January 2023

2022-12-16 09:56 UTC, njlr commented
> @njlr yes I'll squash @Juriyx almost finished a pipeline. So you will be able to consume these fixes at least from the GitHub feed the next week. Release of 2.0 I suppose till the end of the year or January 2023

All done. 

Looking forward to the improvements! :rocket:

2022-12-16 12:09 UTC, xperiandri requested changes
Looks like we had this inconsistency in messages. Are all of them good with these changes?

2022-12-16 12:09 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +            <| GraphQLException ($"{errMsg}Cannot coerce value of type '%O{other.GetType ()}' to list.")
```suggestion
            <| GraphQLException ($"%s{errMsg}Cannot coerce value of type '%O{other.GetType ()}' to list.")
```

2022-12-16 12:09 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +            <| GraphQLException ($"%s{errMsg}expected value of type %s{vardef.TypeDef.ToString ()}, but no value was found.")
```suggestion
            <| GraphQLException ($"%s{errMsg}expected value of type '%s{vardef.TypeDef.ToString ()}', but no value was found.")
```

2022-12-16 12:09 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +                <| GraphQLException ($"%s{errMsg}value of type %O{innerdef.Type} is not assignable from %O{coerced.GetType ()}")
```suggestion
                <| GraphQLException ($"%s{errMsg}value of type '%O{innerdef.Type}' is not assignable from '%O{coerced.GetType ()}'.")
```

2022-12-16 12:09 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +                <| $"%s{errMsg}expected value of type %s{scalardef.Name} but got None"
```suggestion
                <| $"%s{errMsg}expected value of type '%s{scalardef.Name}' but got 'None'."
```

2022-12-16 12:09 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server/Values.fs
> +                <| $"%s{errMsg}Cannot coerce value of type '%O{input.GetType ()}' to type Enum '%s{enumdef.Name}'"
```suggestion
                <| $"%s{errMsg}Cannot coerce value of type '%O{input.GetType ()}' to type Enum '%s{enumdef.Name}'."
```

2022-12-16 12:36 UTC, xperiandri commented
I already have a local commit with fix if you agree with my comments

2022-12-16 12:38 UTC, njlr commented
> I already have a local commit with fix if you agree with my comments

Please go ahead!

2022-12-16 14:04 UTC, merged