LHK-590 add relay project
fsprojects/FSharp.Data.GraphQL pull request #420
Opened 2023-01-18 19:55 UTC by okhorsunenko-lula

2023-01-18 20:16 UTC, xperiandri commented
@andriilula please, review too

2023-01-18 20:19 UTC, xperiandri commented
@okhorsunenko-lula, @andriilula do we need `relay-starter-kit` having `relay-modern-starter-kit`?

2023-01-18 20:43 UTC, xperiandri commented
@okhorsunenko-lula let's format `fields` input parameter in the same way across the solution [FSharp.Data.GraphQL.Relay](https://github.com/Lula-Technologies-Inc/FSharp.Data.GraphQL/tree/LHK-590-implement-graphql-relay-cursor/src/FSharp.Data.GraphQL.Relay)/Connections.fs
either
``` F#
fields = [
	Define.Field("hasNextPage", Boolean, "When paginating forwards, are there more items?", fun _ pageInfo -> pageInfo.HasNextPage)
	Define.Field("hasPreviousPage", Boolean, "When paginating backwards, are there more items?", fun _ pageInfo -> pageInfo.HasPreviousPage)
	Define.Field("startCursor", Nullable String, "When paginating backwards, the cursor to continue.", fun _ pageInfo -> pageInfo.StartCursor)
	Define.Field("endCursor", Nullable String, "When paginating forwards, the cursor to continue.", fun _ pageInfo -> pageInfo.EndCursor)
        ])
```
or
``` F#
fields =
    [ Define.Field("hasNextPage", Boolean, "When paginating forwards, are there more items?", fun _ pageInfo -> pageInfo.HasNextPage)
      Define.Field("hasPreviousPage", Boolean, "When paginating backwards, are there more items?", fun _ pageInfo -> pageInfo.HasPreviousPage)
      Define.Field("startCursor", Nullable String, "When paginating backwards, the cursor to continue.", fun _ pageInfo -> pageInfo.StartCursor)
      Define.Field("endCursor", Nullable String, "When paginating forwards, the cursor to continue.", fun _ pageInfo -> pageInfo.EndCursor) ])
```
What Fantomas will do?

2023-01-18 22:50 UTC, kevin-lula approved these changes
Looks good to me

2023-01-20 06:52 UTC, xperiandri commented
@okhorsunenko-lula so will you replace the old Relay folder content with content from the modern Relay?

2023-01-20 21:46 UTC, xperiandri requested changes
@okhorsunenko-lula, looks good!
Fixing a few comments, rebase and a workflow update left

2023-01-20 21:46 UTC, xperiandri commented on samples/relay-modern-starter-kit/src/app.jsx
> +    `}
Maybe for readability it is better to format without identation?
```suggestion
        query={graphql`
query appQuery($count: Int!, $cursor: String) {
  viewer {
    ...user_viewer
  }
}`}
```

2023-01-20 21:46 UTC, xperiandri commented on samples/relay-modern-starter-kit/src/components/user.jsx
> +    `,
Same here. What do you think?
```suggestion
fragment user_viewer on User {
  widgets(
    first: $count
    after: $cursor
  ) @connection(key: "User_widgets") {
    pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
       }
    edges {
      node {
        id,
        name
      }
    }
  }
}`,
```

2023-01-20 21:46 UTC, xperiandri commented on samples/relay-modern-starter-kit/src/components/user.jsx
> +    `
and here

2023-01-20 21:46 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Relay/FSharp.Data.GraphQL.Relay.fsproj
> +  </ItemGroup>
Rebase this branch using a button in this PR, check it out (rebesed version) and define reference the same as it is done in the other projects

2023-01-20 21:46 UTC, xperiandri commented on samples/star-wars-api/Schema.fs
> +open FSharp.Data.GraphQL.Relay
```suggestion
open FSharp.Data.GraphQL
open FSharp.Data.GraphQL.Types
open FSharp.Data.GraphQL.Relay
open FSharp.Data.GraphQL.Server.Middleware
```

2023-01-20 21:46 UTC, xperiandri commented on samples/star-wars-api/Schema.fs
> +                                | _ -> failwithf "Cursor %A is not 'Friend' global id" after
```suggestion
                                | _ -> failwithf "Cursor %A is not a 'Friend's global id" after
```

2023-01-23 12:52 UTC, okhorsunenko-lula commented on samples/relay-modern-starter-kit/src/components/user.jsx
> +    `,
Yes, it will looks better, thank you
Changed it

2023-01-23 12:53 UTC, okhorsunenko-lula commented on samples/relay-modern-starter-kit/src/app.jsx
> +    `}
Yes, agree with you, it will be better, thanks
Changed it

2023-01-23 20:40 UTC, xperiandri requested changes

2023-01-23 20:40 UTC, xperiandri commented on .github/workflows/publish_ci.yml
> +        dotnet nuget push ../../nuget/*Relay*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}}
Project name must be `FSharp.Data.GraphQL.Server.Relay`
```suggestion
    - name: Pack FSharp.Data.GraphQL.Server.Relay project
      run: |
        cd src/FSharp.Data.GraphQL.Server.Relay
        dotnet pack --no-build --nologo --configuration Release /p:IsNuget=true -o ../../nuget
    - name: Publish FSharp.Data.GraphQL.Server.Relay project to GitHub
      run: |
        cd src/FSharp.Data.GraphQL.Relay
        dotnet nuget push ../../nuget/*Server.Relay*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}}
```

2023-01-23 20:40 UTC, xperiandri commented on .github/workflows/publish_release.yml
> +        dotnet nuget push ../../nuget/*Relay*.nupkg -k ${{secrets.NUGET_SECRET}}
The same

2023-01-23 20:40 UTC, xperiandri commented on FSharp.Data.GraphQL.sln
> +Project("{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}") = "FSharp.Data.GraphQL.Relay", "src\FSharp.Data.GraphQL.Relay\FSharp.Data.GraphQL.Relay.fsproj", "{BC1614A7-D865-44FC-84DF-8F9BE5D44AFA}"
Remember to rename folder too
```suggestion
Project("{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}") = "FSharp.Data.GraphQL.Server.Relay", "src\FSharp.Data.GraphQL.Server.Relay\FSharp.Data.GraphQL.Server.Relay.fsproj", "{BC1614A7-D865-44FC-84DF-8F9BE5D44AFA}"
```

2023-01-24 06:01 UTC, xperiandri commented
@okhorsunenko-lula test Relay again. I made `Edges` not nullable. I don't understand why the original author made them nullable. Have you seen anything about that in spec?

2023-01-27 22:00 UTC, xperiandri requested changes

2023-01-27 22:00 UTC, xperiandri commented on samples/relay-modern-starter-kit/server.fsx
> +            [   Define.GlobalIdField(fun _ w -> w.Id)
Formatting looks incorrect

2023-01-27 22:01 UTC, xperiandri commented
@okhorsunenko-lula we need to test the sample manually again. Then we can merge

2023-02-03 17:14 UTC, okhorsunenko-lula commented
@xperiandri tested, looks good and works, attaching screenshot
Can you please merge it?

![image](https://user-images.githubusercontent.com/104910045/216665516-44c08b20-2cd8-47b7-94c6-22ee2e43f0cb.png)

2023-02-04 00:55 UTC, xperiandri approved these changes

2023-02-04 01:19 UTC, merged