Id type deserialization fix with field tests
fsprojects/FSharp.Data.GraphQL pull request #427
Opened 2023-02-24 20:14 UTC by xperiandri

@ivelten I think testing should happen from here.
Also, we can change some `id` fields on StarWars API to cover different scenarios

2023-10-13 20:12 UTC, xperiandri commented
Probably we need to modify some tests too

2023-10-15 10:17 UTC, valbers requested changes
Please respond my comment.

2023-10-15 10:17 UTC, valbers commented on src/FSharp.Data.GraphQL.Client/BaseTypes.fs
> +                        s |> makeSomeIfNeeded
did this really fix the issue? This surprises me, since there is already an arm covering both cases (the default one) and doing the same.

2024-09-01 20:49 UTC, valbers commented
I'll believe in you and assume I'm missing something. Let's close this PR.

2024-09-01 20:49 UTC, valbers approved these changes

2024-09-02 12:43 UTC, merged