Implemented ValueObjectScalarDefinition, fixed built-in scalars input coercion
fsprojects/FSharp.Data.GraphQL pull request #439
Opened 2023-08-27 21:24 UTC by xperiandri

* Added `ValueObjectScalarDefinition`
* Changed `IDType` implementation to support only string and int64 Ids
* Fixed built-in scalars input coercion and added tests for that

2023-08-28 05:39 UTC, mickhansen commented
Would it be possible to add some tests over `ValueObjectScalarDefinition` / `ValueObject`? 
I'm not quite seeing the purpose of the new definition, tests might help clarify that for me.

2023-08-28 22:03 UTC, xperiandri commented
Good point, I'll add.
The main idea is that you have a basic primitive like string and a wrapped value object like `type MyId = Id of Guid`.
So from the variable string comes to coercion function and then you perform custom processing.
If you define a scalar of `MyId` you will have to have a variable to be `MyId` on variables coercion, and on inline value parsing of AST. The first one is in theory more or less possible but the second one I do not know how to perform.

2023-08-28 22:03 UTC, valbers commented
I agree with @mickhansen regarding the question about the purpose of `ValueObjectScalarDefinition`, besides I'm struggling to find it a good naming. In the end, the definition of `ValueObjectScalarDefinition` doesn't imply any value object of sorts, it's simply a further generalization of `ScalarDefinition<'Val>` such that `type ScalarDefinition<'Val> = ValueObjectScalarDefinition<'Val, 'Val>`.
So I'd recommend to at least change the name to something like `type AssymetricScalarDefinition<'CoercedValue, 'CoercedInput>`

2023-08-28 22:05 UTC, xperiandri commented
Probably it can become `ScalarDefinition'2` as it will not conflict with `ScalarDefinition'1` 🙂

2023-08-28 22:08 UTC, valbers requested changes
Please address the open points and then I can approve your PR.

2023-08-28 22:08 UTC, valbers commented on tests/FSharp.Data.GraphQL.Tests/Variables and Inputs/CoercionTests.fs
> +    | Error _ -> Assert.Fail $"Expected %A{actual} to be able to be coerced to %A{expected}"
nice 👌

2023-08-28 22:08 UTC, valbers commented on tests/FSharp.Data.GraphQL.Tests/Variables and Inputs/CoercionTests.fs
> +let private testCoercionError graphQLType (expectedErrorMeesage: string) actual =
```suggestion
let private testCoercionError graphQLType (expectedErrorMessage: string) actual =
```

2023-08-28 22:08 UTC, valbers commented on tests/FSharp.Data.GraphQL.Tests/Variables and Inputs/CoercionTests.fs
> +    testCoercionError IntType "Inline value '123,4' of type float cannot be converted into integer of range from -2147483648 to 2147483647" (InlineConstant (FloatValue 123.4))
What about this comma (i.e. `,`) here in the number? I think it would be better to have a dot representation which is "canonical" (we define floats with a dot). Besides, this test will probably behave differently on another machine with a culture that uses dots in numbers with decimal points.

2023-08-28 22:08 UTC, valbers commented on tests/FSharp.Data.GraphQL.Tests/Variables and Inputs/CoercionTests.fs
> +    testCoercionError LongType "Inline value '123,4' of type float cannot be converted into integer of range from -9223372036854775808 to 9223372036854775807" (InlineConstant (FloatValue 123.4))
here the comma thing again.

2023-08-28 22:08 UTC, valbers commented on tests/FSharp.Data.GraphQL.Tests/Variables and Inputs/CoercionTests.fs
> +    testCoercionError IDType "Inline value '123,4' of type float cannot be converted into identifier of range from -9223372036854775808 to 9223372036854775807" (InlineConstant (FloatValue 123.4))
comma (just so you don't forget).

2023-08-28 22:08 UTC, valbers commented on src/FSharp.Data.GraphQL.Shared/SchemaDefinitions.fs
> +            Error [{ new IGQLError with member _.Message = $"Inline value '%s{value}' cannot be paprsed into %s{destinationType}" }]
```suggestion
            Error [{ new IGQLError with member _.Message = $"Inline value '%s{value}' cannot be parsed into %s{destinationType}" }]
```

2023-08-29 05:44 UTC, mickhansen commented
> Good point, I'll add. The main idea is that you have a basic primitive like string and a wrapped value object like `type MyId = Id of Guid`. So from the variable string comes to coercion function and then you perform custom processing. If you define a scalar of `MyId` you will have to have a variable to be `MyId` on variables coercion, and on inline value parsing of AST. The first one is in theory more or less possible but the second one I do not know how to perform.

That sounds like a good usecase! Just wasn't familiar with the `ValueObject` terminology.

2023-09-12 00:41 UTC, xperiandri commented
@valbers your comments are resolved. Thanks for the very valuable feedback!

2023-09-12 02:19 UTC, GBirkel approved these changes

2023-09-16 14:07 UTC, valbers approved these changes
Looks good to me ™️

2023-09-17 14:14 UTC, merged