Relay Revamp
fsprojects/FSharp.Data.GraphQL pull request #484
Opened 2024-07-05 17:24 UTC by njlr

The existing [relay pagination](https://relay.dev/graphql/connections.htm) code was synchronous, and therefore not usable against a real data-store. 

This PR makes the types async and introduces some strong typing. This is a breaking change. 

I also removed the old Relay sample, which no longer works anyway, and have added a new pagination sample. 

The sample queries data from SQLite, which shows that it can work for real data-stores. The example is efficient in terms of data-fetching.

2024-07-06 00:51 UTC, xperiandri commented
Wow! Cool! I’ll review this weekend

2024-07-06 19:17 UTC, njlr commented
> Wow! Cool! I’ll review this weekend

I need to update a few more things to fix the build first :+1:

2024-07-07 23:11 UTC, xperiandri commented
Let's migrate to `voption` (when reasonable) and interpolated strings in the code you change

2024-07-19 18:24 UTC, njlr commented
> > Wow! Cool! I’ll review this weekend
> 
> I need to update a few more things to fix the build first 👍

Now ready :+1:

2024-08-31 14:02 UTC, xperiandri requested changes
@njlr amazing job! Could you address a few remarks, please?

2024-08-31 14:02 UTC, xperiandri commented on Packages.props
> +    <PackageReference Update="Donald" Version="10.1.0" />
Could you sort them by name, please? Within all the list

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Prelude.fs
> +        let memoize (workflow : Async<'t>) : Async<'t> =
Could you add XML comment explaining this?

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +            let fetchItems =
Could you annotate each value here with a comment explaining what it is for?
This will help newcomers to faster adapt your sample to their problem

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +                |> Async.memoize
```suggestion
                // Store the result similar to what Task does so that we don't go to DB multiple times for the same data
                |> Async.memoize
```

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +                    let! items = root.FetchBooksPage (after, true, false, 1)
```suggestion
                    // Retrieve one item backward
                    let! items = root.FetchBooksPage (after, isCursorInclusive  = true, isForward = false, limit = 1)
```

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +                    return List.length items > last
This needs explanation

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +                    let! items = root.FetchBooksPage (before, true, true, 1)
```suggestion
                    // Retrieve one item forward
                    let! items = root.FetchBooksPage (before, isCursorInclusive  = true, isForward  = true, limit = 1)
```

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +                    return List.length items > first
same here

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +                    | Backward _ -> items |> List.truncate sliceInfo.PageSize |> List.rev
I wonder how many items will we have and shouldn't we apply rev first on line 131?

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/Schema.fs
> +            }
Why don't you memoize edges? You use them twice below
Maybe they should be materialized?

2024-08-31 14:02 UTC, xperiandri commented on samples/relay-book-store/relay-book-store.fsproj
> +    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" />
```suggestion
    <PackageReference Include="Donald" />
    <PackageReference Include="FsToolkit.ErrorHandling" />
    <PackageReference Include="Giraffe" />
    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="System.Data.Common" />
    <PackageReference Include="Thoth.Json.Net" />
```

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +}
Is your intent to execute code only if the field is specified in a query?

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +    | Forward of first : int * after : 'Cursor option
Let's rename to capital and migrate to voption. It will go to v3 with breaking changes
```suggestion
    | Forward of First : int * After : 'Cursor voption
```

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +    | Backward of last : int * before : 'Cursor option
```suggestion
    | Backward of Last : int * Before : 'Cursor option
```

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +    let (|SliceInfo|_|) (ctx : ResolveFieldContext) =
```suggestion
    [<return: Struct>]
    let (|SliceInfo|_|) (ctx : ResolveFieldContext) =
```

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +        | Some (first), (after) -> Some (Forward (first, after))
```suggestion
        | ValueSome (first), None -> ValueSome (Forward (first, None))
        | ValueSome (first), (after) -> ValueSome (Forward (first, after))
```

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +            | Some (last), (before) -> Some (Backward (last, before))
```suggestion
            | ValueSome (last), None -> ValueSome (Backward (last, None))
            | ValueSome (last), (before) -> ValueSome (Backward (last, before))
```

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +        )
I would probably leave this block as is but up to you

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +            )
Maybe, like this to keep a single line? Typo in definitions
```suggestion
        | List _ ->
            failwith $"{nodeType.ToString ()} cannot be used as a relay Edge or Connection - only non-list type definitions are allowed"
```

2024-08-31 14:02 UTC, xperiandri commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +                    + n.Name,
Same here
```suggestion
                description = $"An edge in a connection from an object to another object of type {n.Name}",
```

2024-08-31 14:02 UTC, xperiandri commented on tests/FSharp.Data.GraphQL.Tests/Relay/ConnectionTests.fs
> +    }
Maybe, just `async.Result` in such sync pipe cases?
```suggestion
    Edges =
        slice
        |> List.map (fun s -> { Node = s; Cursor = cursor s })
        |> List.toSeq
        |> async.Result
```

2024-08-31 14:02 UTC, xperiandri commented on tests/FSharp.Data.GraphQL.Tests/Relay/ConnectionTests.fs
> +            "strings", upcast NameValueLookup.ofList [ "edges", upcast [ box <| NameValueLookup.ofList [ "node", upcast "five" ] ] ]
I would keep this as before for readability

2024-08-31 17:08 UTC, xperiandri commented
@njlr if you can address that for tomorrow I will review and merge that immediately and issue the new version of the packages as I want to use your new changes

2024-09-01 09:11 UTC, njlr commented on src/FSharp.Data.GraphQL.Server.Relay/Connections.fs
> +}
Yes. Here `async` is used to make it lazy.

2024-09-01 09:55 UTC, njlr commented on samples/relay-book-store/Schema.fs
> +                    | Backward _ -> items |> List.truncate sliceInfo.PageSize |> List.rev
* In the forward case, we asked for `first + 1` items, but the edges should only contain `first` items
 * In the backward case, we asked for `last + 1` items, but the edges should only contain `last` items
 * We only need to reverse in the backward case

2024-09-01 10:06 UTC, njlr commented
Comments addressed :+1:

2024-09-01 10:42 UTC, xperiandri approved these changes

2024-09-01 10:54 UTC, xperiandri approved these changes

2024-09-01 10:54 UTC, xperiandri approved these changes

2024-09-01 11:39 UTC, xperiandri commented
Amazing! @njlr have a look at my last changes

2024-09-01 13:18 UTC, merged